force-app/main/default/objects/Account/fields/Business_Central_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Central_Id__c</fullName>
    <externalId>true</externalId>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Error__c/Sync_Error__c.object-meta.xml
<CustomObject>
    <label>Sync Error</label>
    <nameField>
        <displayFormat>SE-{00000}</displayFormat>
        <label>Sync Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Error__c/fields/Business_Central_Id__c.field-meta.xml
<CustomField>
    <fullName>Business_Central_Id__c</fullName>
    <label>Business Central Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Error__c/fields/Resolution_Status__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Status__c</fullName>
    <label>Resolution Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Not Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DetailButtonController.cls
/**
 * @Version: 1.0
 * @Author: Frederik
 * @Copyright: 2021 Upeo Consulting
 * @Uses:
 *
 * -----------------------------------------------------------------------------------------------
 * Description: 
 *
 *
 * Created: 5/10/2022
 * Last Updated: 5/10/2022
 *
 * Unit tests:
 *
 * Change log:
 * -----------------------------------------------------------------------------------------------
*/
public with sharing class DetailButtonController
{

    private ApexPages.StandardController standardController;


    public DetailButtonController(ApexPages.StandardController standardController) {
        this.standardController = standardController;
    }



    public pageReference  doSomething() {
        // Apex code for handling record from a Detail page goes here
        Id recordId = standardController.getId();
        Sync_Error__c record = [SELECT Id, Name, Type__c,Business_Central_Id__c, Resolution_Status__c FROM Sync_Error__c WHERE Id = :recordId];
        String result;
        Boolean success = true;
        String returnMessage = null;
        If(record != null) {
            System.debug('record: ' + record);
            if(record.Type__c == 'Invoice Upsert') {
                BusinessCentralSyncService.getInvoiceDataSingle(record.Business_Central_Id__c);
                record.Resolution_Status__c = 'Resolved';
                update record;
            }
            if(record.Type__c == 'Account') {
                BusinessCentralSyncService.getSingleAccountData(record.Business_Central_Id__c);
                record.Resolution_Status__c = 'Resolved';
                update record;
            }
            if(record.Type__c == 'Account Upsert') {
                BusinessCentralSyncService.getSingleAccountData(record.Business_Central_Id__c);
                record.Resolution_Status__c = 'Resolved';
                update record;
            }
        }
        PageReference pageRef = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/' + recordId);
        pageRef.setRedirect(true);
        return pageRef;
    }

}